---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:522814735019:task-definition/python:1"
        LoadBalancerInfo:
          ContainerName: "container2"
          ContainerPort: 5000
